"""create pin reports table

Revision ID: 06ff1a3f8340
Revises: 5a2b98650463
Create Date: 2026-01-28 17:08:46.977997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ff1a3f8340'
down_revision: Union[str, Sequence[str], None] = '5a2b98650463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_reports',
    sa.Column('pin_report_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pin_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.Enum('INACCURATE', 'RESOLVED', 'DUPLICATE', 'EXPIRED', 'MISLEADING', 'SPAM', 'INAPPROPRIATE', name='pinreporttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.pin_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pin_report_id')
    )
    op.create_index(op.f('ix_pin_reports_pin_report_id'), 'pin_reports', ['pin_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pin_reports_pin_report_id'), table_name='pin_reports')
    op.drop_table('pin_reports')
    # ### end Alembic commands ###
