"""add user_use_displayname column

Revision ID: 1a361f90b479
Revises: 547c827d02d2
Create Date: 2026-03-10 16:35:36.639855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a361f90b479'
down_revision: Union[str, Sequence[str], None] = '547c827d02d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_sharing_loc_share_id'), table_name='location_sharing')
    op.drop_table('location_sharing')
    op.add_column('category_levels', sa.Column('cat_level_color', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'category_levels', ['cat_level_color'])
    op.alter_column('pins', 'pin_title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.add_column('users', sa.Column('user_use_displayname', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_use_displayname')
    op.alter_column('pins', 'pin_title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_constraint(None, 'category_levels', type_='unique')
    op.drop_column('category_levels', 'cat_level_color')
    op.create_table('location_sharing',
    sa.Column('loc_share_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('target_user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('user_id <> target_user_id', name=op.f('check_no_self_location_share')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], name=op.f('location_sharing_target_user_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('location_sharing_user_id_fkey')),
    sa.PrimaryKeyConstraint('loc_share_id', name=op.f('location_sharing_pkey')),
    sa.UniqueConstraint('user_id', 'target_user_id', name=op.f('unique_location_sharing_pair'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_location_sharing_loc_share_id'), 'location_sharing', ['loc_share_id'], unique=False)
    # ### end Alembic commands ###
