"""create user relationship table

Revision ID: 21d69af94a13
Revises: cf8839ca8355
Create Date: 2026-01-28 18:09:20.604334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21d69af94a13'
down_revision: Union[str, Sequence[str], None] = 'cf8839ca8355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationships',
    sa.Column('user_rel_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_rel_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED', name='userrelationshiptype'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_id <> target_user_id', name='check_no_self_user_rel'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_rel_id'),
    sa.UniqueConstraint('user_id', 'target_user_id', name='unique_user_rel_pair')
    )
    op.create_index(op.f('ix_user_relationships_user_rel_id'), 'user_relationships', ['user_rel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_relationships_user_rel_id'), table_name='user_relationships')
    op.drop_table('user_relationships')
    # ### end Alembic commands ###
