"""create user reports table

Revision ID: 4492da9c19a4
Revises: 96913d3c5cc2
Create Date: 2026-01-28 17:17:47.001866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4492da9c19a4'
down_revision: Union[str, Sequence[str], None] = '96913d3c5cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_reports',
    sa.Column('user_report_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reported_user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', sa.Enum('BOT', 'PROFANITY', 'SPAM', 'INAPPROPRIATE_CONTENT', 'HARASSMENT', 'SCAM', 'IMPERSONATION', 'HATE_SPEECH', name='userreporttype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_report_id')
    )
    op.create_index(op.f('ix_user_reports_user_report_id'), 'user_reports', ['user_report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_reports_user_report_id'), table_name='user_reports')
    op.drop_table('user_reports')
    # ### end Alembic commands ###
