"""add sharing_expires_at to user_locations

Revision ID: 50da653d7345
Revises: b7ca2966177e
Create Date: 2026-05-17 19:17:25.281951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50da653d7345'
down_revision: Union[str, Sequence[str], None] = 'b7ca2966177e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('sharing_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_locations', 'sharing_expires_at')
    # ### end Alembic commands ###
