"""Create user_locations and location_permissions tables

Revision ID: 547c827d02d2
Revises: 3a1312bd3347
Create Date: 2026-03-01 16:12:30.619042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '547c827d02d2'
down_revision: Union[str, Sequence[str], None] = '3a1312bd3347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_locations',
    sa.Column('user_loc_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_loc_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_locations_user_loc_id'), 'user_locations', ['user_loc_id'], unique=False)
    op.create_table('location_permissions',
    sa.Column('loc_perm_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_loc_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_loc_id'], ['user_locations.user_loc_id'], ),
    sa.PrimaryKeyConstraint('loc_perm_id')
    )
    op.create_index(op.f('ix_location_permissions_loc_perm_id'), 'location_permissions', ['loc_perm_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_permissions_loc_perm_id'), table_name='location_permissions')
    op.drop_table('location_permissions')
    op.drop_index(op.f('ix_user_locations_user_loc_id'), table_name='user_locations')
    op.drop_table('user_locations')
    # ### end Alembic commands ###
