"""create categories table

Revision ID: 5861f6ada857
Revises: bb65deed9910
Create Date: 2026-01-28 16:25:27.971616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5861f6ada857'
down_revision: Union[str, Sequence[str], None] = 'bb65deed9910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('cat_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('cat_level_id', sa.SmallInteger(), nullable=True),
    sa.Column('cat_name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['cat_level_id'], ['category_levels.cat_level_id'], ),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_index(op.f('ix_categories_cat_id'), 'categories', ['cat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_cat_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
