"""create pin reaction table

Revision ID: 5a2b98650463
Revises: 863c810e3973
Create Date: 2026-01-28 16:59:39.131373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2b98650463'
down_revision: Union[str, Sequence[str], None] = '863c810e3973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pin_reactions',
    sa.Column('reaction_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pin_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reaction_value', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reaction_value IN (1, -1)', name='check_reaction_value'),
    sa.ForeignKeyConstraint(['pin_id'], ['pins.pin_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('reaction_id')
    )
    op.create_index(op.f('ix_pin_reactions_reaction_id'), 'pin_reactions', ['reaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pin_reactions_reaction_id'), table_name='pin_reactions')
    op.drop_table('pin_reactions')
    # ### end Alembic commands ###
