"""create user bans table

Revision ID: 61d159131fbd
Revises: 24c1983448c1
Create Date: 2026-01-28 17:32:23.376252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d159131fbd'
down_revision: Union[str, Sequence[str], None] = '24c1983448c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bans',
    sa.Column('ban_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('ban_type', sa.Enum('PERMANENT', 'TEMPORARY', name='userbantype'), nullable=False),
    sa.Column('ban_expiry', sa.DateTime(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=False),
    sa.Column('ban_isactive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ban_id')
    )
    op.create_index(op.f('ix_user_bans_ban_id'), 'user_bans', ['ban_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bans_ban_id'), table_name='user_bans')
    op.drop_table('user_bans')
    # ### end Alembic commands ###
