"""create pins table

Revision ID: 863c810e3973
Revises: 9b097d6636ba
Create Date: 2026-01-28 16:49:50.029371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '863c810e3973'
down_revision: Union[str, Sequence[str], None] = '9b097d6636ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pins',
    sa.Column('pin_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cat_id', sa.SmallInteger(), nullable=False),
    sa.Column('sub_cat_id', sa.SmallInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pin_title', sa.String(length=30), nullable=False),
    sa.Column('pin_description', sa.String(length=300), nullable=True),
    sa.Column('pin_picture_path', sa.String(length=500), nullable=True),
    sa.Column('pin_latitude', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('pin_longitude', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('pin_isactive', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('pin_expire_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.cat_id'], ),
    sa.ForeignKeyConstraint(['sub_cat_id'], ['sub_categories.sub_cat_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('pin_id')
    )
    op.create_index(op.f('ix_pins_pin_id'), 'pins', ['pin_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pins_pin_id'), table_name='pins')
    op.drop_table('pins')
    # ### end Alembic commands ###
