"""add sub category table

Revision ID: 9b097d6636ba
Revises: e5676b6099dd
Create Date: 2026-01-28 16:35:04.880778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b097d6636ba'
down_revision: Union[str, Sequence[str], None] = 'e5676b6099dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_categories',
    sa.Column('sub_cat_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('cat_id', sa.SmallInteger(), nullable=False),
    sa.Column('sub_cat_name', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['categories.cat_id'], ),
    sa.PrimaryKeyConstraint('sub_cat_id')
    )
    op.create_index(op.f('ix_sub_categories_sub_cat_id'), 'sub_categories', ['sub_cat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_categories_sub_cat_id'), table_name='sub_categories')
    op.drop_table('sub_categories')
    # ### end Alembic commands ###
