"""create category levels table

Revision ID: bb65deed9910
Revises: bcbb1967fb43
Create Date: 2026-01-28 15:57:16.115329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb65deed9910'
down_revision: Union[str, Sequence[str], None] = 'bcbb1967fb43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_levels',
    sa.Column('cat_level_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('cat_level_name', sa.String(length=60), nullable=False),
    sa.Column('cat_level_ttl_mins', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('cat_level_id'),
    sa.UniqueConstraint('cat_level_name')
    )
    op.create_index(op.f('ix_category_levels_cat_level_id'), 'category_levels', ['cat_level_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_levels_cat_level_id'), table_name='category_levels')
    op.drop_table('category_levels')
    # ### end Alembic commands ###
