"""create location sharing table

Revision ID: cf8839ca8355
Revises: 1b275a244195
Create Date: 2026-01-28 17:53:07.559186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8839ca8355'
down_revision: Union[str, Sequence[str], None] = '1b275a244195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_sharing',
    sa.Column('loc_share_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_id <> target_user_id', name='check_no_self_location_share'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('loc_share_id'),
    sa.UniqueConstraint('user_id', 'target_user_id', name='unique_location_sharing_pair')
    )
    op.create_index(op.f('ix_location_sharing_loc_share_id'), 'location_sharing', ['loc_share_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_sharing_loc_share_id'), table_name='location_sharing')
    op.drop_table('location_sharing')
    # ### end Alembic commands ###
