"""fix nullable fk key

Revision ID: e5676b6099dd
Revises: 5861f6ada857
Create Date: 2026-01-28 16:27:18.884554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5676b6099dd'
down_revision: Union[str, Sequence[str], None] = '5861f6ada857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'cat_level_id',
               existing_type=sa.SMALLINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'cat_level_id',
               existing_type=sa.SMALLINT(),
               nullable=True)
    # ### end Alembic commands ###
